export default function handler(req, res) {
  return res.status(200).json({ locations: [
    {"description":"Aberdeen","shortCodes":["ABD"]},
    {"description":"Basingstoke","shortCodes":["BSK"]},
    {"description":"Bath Spa","shortCodes":["BTH"]},
    {"description":"Birmingham New Street","shortCodes":["BHM"]},
    {"description":"Brighton","shortCodes":["BTN"]},
    {"description":"Bristol Temple Meads","shortCodes":["BRI"]},
    {"description":"Cambridge","shortCodes":["CBG"]},
    {"description":"Cardiff Central","shortCodes":["CDF"]},
    {"description":"Clapham Junction","shortCodes":["CLJ"]},
    {"description":"East Croydon","shortCodes":["ECR"]},
    {"description":"Edinburgh Waverley","shortCodes":["EDB"]},
    {"description":"Exeter St Davids","shortCodes":["EXD"]},
    {"description":"Gatwick Airport","shortCodes":["GTW"]},
    {"description":"Glasgow Central","shortCodes":["GLC"]},
    {"description":"Guildford","shortCodes":["GLD"]},
    {"description":"Leeds","shortCodes":["LDS"]},
    {"description":"Liverpool Lime Street","shortCodes":["LIV"]},
    {"description":"London Bridge","shortCodes":["LBG"]},
    {"description":"London Charing Cross","shortCodes":["CHX"]},
    {"description":"London Euston","shortCodes":["EUS"]},
    {"description":"London Kings Cross","shortCodes":["KGX"]},
    {"description":"London Liverpool Street","shortCodes":["LST"]},
    {"description":"London Marylebone","shortCodes":["MYB"]},
    {"description":"London Paddington","shortCodes":["PAD"]},
    {"description":"London St Pancras International","shortCodes":["STP"]},
    {"description":"London Victoria","shortCodes":["VIC"]},
    {"description":"London Waterloo","shortCodes":["WAT"]},
    {"description":"Manchester Piccadilly","shortCodes":["MAN"]},
    {"description":"Newcastle","shortCodes":["NCL"]},
    {"description":"Norwich","shortCodes":["NRW"]},
    {"description":"Nottingham","shortCodes":["NOT"]},
    {"description":"Oxford","shortCodes":["OXF"]},
    {"description":"Reading","shortCodes":["RDG"]},
    {"description":"Sheffield","shortCodes":["SHF"]},
    {"description":"Southampton Central","shortCodes":["SOU"]},
    {"description":"Surbiton","shortCodes":["SUR"]},
    {"description":"Wimbledon","shortCodes":["WIM"]},
    {"description":"Winchester","shortCodes":["WIN"]},
    {"description":"Woking","shortCodes":["WOK"]},
    {"description":"York","shortCodes":["YRK"]}
  ]});
}
